service:
  flush: 5

pipeline:
  inputs:
    - name: dummy
      dummy: '{"SeverityText": "Info", "Body": "hello from dummy input", "Attributes": {"key1": "value1", "key2": "value2"}}'

  outputs:
    - name: azure_logs_ingestion
      match: '*'
      table_name: MyFluentBitLogs
      dce_url: ${DCE_URL}
      dcr_id: ${DCR_ID}
      tenant_id: ${TENANT_ID}
      client_id: ${CLIENT_ID}
      client_secret: ${CLIENT_SECRET}
      time_key: TimeGenerated
      time_generated: true
