#!/usr/bin/env bash

set -eo pipefail

# TODO:
# - Remove endpoint creation if it's not needed

export SUBSCRIPTION_ID="21f320bb-0abe-407e-aba8-480d084c058c"
export RESOURCE_GROUP="azure-monitor-test"
export WORKSPACE_NAME="azure-monitor-test"
export ENDPOINT_NAME="azure-monitor-test-endpoint"
export RULE_NAME="azure-monitor-test-rule"
export LOCATION="centralus"
export RESOURCE_GROUP_PORTAL_URL="https://portal.azure.com/#@chrissidigmail.onmicrosoft.com/resource/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/overview"

envsubst < dcr.json.tmpl > dcr.json

echo "Checking login status..."
az account show || jq -r '.id' > /dev/null || { echo "Not logged in. Please run 'az login'."; exit 1; }

az account set --subscription "$SUBSCRIPTION_ID"
# az config set defaults.group="$RESOURCE_GROUP"
# az config set defaults.location="$LOCATION"

az extension add --name monitor-control-service

echo "Creating resource group..."
az group create --resource-group "$RESOURCE_GROUP" --location "$LOCATION"

echo "Creating log analytics workspace..."
az monitor log-analytics workspace create --resource-group "$RESOURCE_GROUP" --workspace-name "$WORKSPACE_NAME"

echo "Creating data collection endpoint..."
az monitor data-collection endpoint create --resource-group "$RESOURCE_GROUP" --name "$ENDPOINT_NAME" --public-network-access "Enabled"

echo "Creating data collection rule..."
az monitor data-collection rule create --resource-group "$RESOURCE_GROUP" --rule-name "$RULE_NAME" --data-collection-endpoint-id "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Insights/dataCollectionEndpoints/$ENDPOINT_NAME" --rule-file dcr.json

echo "Creating service principal and assigning role..."
az ad sp create-for-rbac --name fluent-bit-logger --role "Monitoring Metrics Publisher" --scopes "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP"

open "$RESOURCE_GROUP_PORTAL_URL"
