#!/usr/bin/env bash

set -eo pipefail

export SUBSCRIPTION_ID="21f320bb-0abe-407e-aba8-480d084c058c"
export BASE_NAME="az-monitor-otel-logs-2"
export RESOURCE_GROUP="${BASE_NAME}-rg"
export WORKSPACE_NAME="${BASE_NAME}-workspace"
export ENDPOINT_NAME="${BASE_NAME}-endpoint"
export SP_NAME="${BASE_NAME}-sp"
export RULE_NAME="${BASE_NAME}-rule"
export LOCATION="centralus"
export LOGS_QUERY_URL="https://portal.azure.com/#@chrissidigmail.onmicrosoft.com/resource/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.OperationalInsights/workspaces/${WORKSPACE_NAME}/logs"

mkdir -p $BASE_NAME

envsubst < dcr.json.tmpl > dcr.json

echo "Checking login status..."
az account show || jq -r '.id' > /dev/null || { echo "Not logged in. Please run 'az login'."; exit 1; }

az account set --subscription "$SUBSCRIPTION_ID"
# az config set defaults.group="$RESOURCE_GROUP"
# az config set defaults.location="$LOCATION"

az extension add --name monitor-control-service

echo "Creating resource group..."
az group create --resource-group "$RESOURCE_GROUP" --location "$LOCATION"

echo "Creating log analytics workspace..."
az monitor log-analytics workspace create --resource-group "$RESOURCE_GROUP" --workspace-name "$WORKSPACE_NAME"

# echo "Creating data collection endpoint..."
# az monitor data-collection endpoint create --resource-group "$RESOURCE_GROUP" --name "$ENDPOINT_NAME" --public-network-access "Enabled" | tee "$BASE_NAME/endpoint.json"

# echo "Creating data collection rule that uses endpoint..."
# az monitor data-collection rule create --resource-group "$RESOURCE_GROUP" --rule-name "$RULE_NAME" --data-collection-endpoint-id "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Insights/dataCollectionEndpoints/$ENDPOINT_NAME" --rule-file dcr.json | tee "$BASE_NAME/dcr.json"

echo "Creating direct data collection rule..."
# --kind "Direct" in place of creating and referencing a data collection endpoint
# endpoints.logsIngestion can be read from the DCR output
az monitor data-collection rule create --resource-group "$RESOURCE_GROUP" --rule-name "$RULE_NAME" --kind "Direct" --rule-file dcr.json | tee "$BASE_NAME/dcr.json"

echo "Creating service principal and assigning role..."
az ad sp create-for-rbac --name "$SP_NAME" --role "Monitoring Metrics Publisher" --scopes "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP" | tee "$BASE_NAME/service-principal.json"

open "$LOGS_QUERY_URL"
