service:
  flush: 1

pipeline:
  inputs:
    - name: opentelemetry
      listen: 127.0.0.1
      port: 4318

  filters:
    # log seems to be the only key set
    # everything else is metadata and group attributes
    # it's not possible to match service.name, severity_text, etc
    - name: rewrite_tag
      match: 'v1_logs'
      rule: $log . $log false
      emitter_name: re_emitted

  # TODO: add multiple opentelemetry outputs with different destinations,
  # once we get rewrite_tag working in a way that's useful
  outputs:
    # debug output
    # stdout includes metadata and group attributes
    - name: stdout
      match: '*'

    # debug output
    # file output does not include metadata and group attributes
    # you'll only find the timestamp and the log message in the output
    - name: file
      match: '*'

    - name: opentelemetry
      match: '*'
      host: ${LOGS_DCE_HOST}
      port: 443
      tls: on
      tls.verify: on
      logs_uri: /dataCollectionRules/${DCR_IMMUTABLE_ID}/streams/Microsoft-OTLP-Logs/otlp/v1/logs

      # Microsoft Entra OAuth 2.0 client-credentials auth.
      oauth2.enable: true
      oauth2.token_url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
      oauth2.client_id: ${CLIENT_ID}
      oauth2.client_secret: ${CLIENT_SECRET}
      oauth2.scope: https://monitor.azure.com/.default
      oauth2.auth_method: post
